-- PHB Feats seed (all 42 including Grappler)
SET NAMES utf8mb4;
INSERT INTO feats (index_name, name, description, prerequisites) VALUES
('actor','Actor','Skilled at mimicry and dramatics, you gain +1 Charisma, advantage on Deception/Performance when disguised, and can mimic voices or sounds you have heard.','None'),
('alert','Alert','Always on the lookout for danger: +5 bonus to initiative, can''t be surprised while conscious, hidden creatures gain no advantage on attacks against you.','None'),
('athlete','Athlete','You have undergone extensive physical training: +1 Str or Dex, standing up uses only 5 ft of movement, climbing doesn''t halve speed, you can make a running long/high jump after moving only 5 ft.','None'),
('charger','Charger','When you use your action to Dash, you can use a bonus action to make one melee attack or shove, adding +5 damage if you moved 10 ft in a straight line.','None'),
('crossbow-expert','Crossbow Expert','You ignore the loading property of crossbows, don''t have disadvantage when firing in melee range, and can attack with a hand crossbow as a bonus action when you attack with a one-handed weapon.','None'),
('defensive-duelist','Defensive Duelist','When wielding a finesse weapon you are proficient with, you can use your reaction to add your proficiency bonus to AC against one melee attack that would hit you.','Dexterity 13'),
('dual-wielder','Dual Wielder','You master fighting with two weapons: +1 AC while wielding two melee weapons, can use two-weapon fighting with non-light weapons, and can draw or stow two weapons at once.','None'),
('dungeon-delver','Dungeon Delver','Alert to the perils of dungeons: advantage on Perception and Investigation to detect secret doors, advantage on saves vs. traps, resistance to trap damage, can search for traps at normal pace.','None'),
('durable','Durable','Hardy and resilient: +1 Constitution, when you roll Hit Dice to regain hp, the minimum hp regained equals twice your Constitution modifier (minimum 2).','None'),
('elemental-adept','Elemental Adept','Choose acid, cold, fire, lightning, or thunder. Spells you cast ignore resistance to that damage type, and when you roll damage for such a spell, treat any 1 on a die as a 2.','Spellcasting ability'),
('grappler','Grappler','You''ve developed the skills necessary to hold your own in close-quarters grappling: advantage on attack rolls against a creature you are grappling, and you can use your action to try to pin it (restrained).','Strength 13'),
('great-weapon-master','Great-Weapon Master','When you score a critical hit or reduce a creature to 0 hp with a heavy melee weapon, you can make one melee weapon attack as a bonus action. You can also choose -5 to hit for +10 damage.','None'),
('healer','Healer','You are an able physician: using a healer''s kit stabilises a creature without a check; using the kit as an action restores 1d6+4 hp plus HD, once per creature per short rest.','None'),
('heavily-armored','Heavily Armored','+1 Strength and proficiency with heavy armor.','Proficiency with medium armor'),
('heavy-armor-master','Heavy Armor Master','+1 Strength; while wearing heavy armor, bludgeoning, piercing, and slashing damage from non-magical attacks is reduced by 3.','Proficiency with heavy armor'),
('inspiring-leader','Inspiring Leader','After a 10-minute speech, up to 6 allies who can hear you gain temporary hp equal to your level + Charisma modifier.','Charisma 13'),
('keen-mind','Keen Mind','+1 Intelligence; you always know north, the number of hours until sunrise/sunset, and can recall anything you saw or heard in the past month.','None'),
('lightly-armored','Lightly Armored','+1 Strength or Dexterity and proficiency with light armor.','None'),
('linguist','Linguist','+1 Intelligence, learn 3 languages of your choice, and you can create written ciphers only you or those you teach can decipher.','None'),
('lucky','Lucky','You have inexplicable luck. You have 3 luck points per long rest. Spend one to roll an extra d20 on an attack, ability check, or save (choose which d20 to use), or force an attacker to reroll their attack.','None'),
('mage-slayer','Mage Slayer','When a creature within 5 ft casts a spell, you can use your reaction to make a melee attack against it; you cause disadvantage on its Concentration save, and you have advantage on saves against spells cast by creatures within 5 ft.','None'),
('magic-initiate','Magic Initiate','Choose a class: bard, cleric, druid, sorcerer, warlock, or wizard. Learn 2 cantrips and one 1st-level spell from that class''s list; you can cast the spell once per long rest without a slot.','None'),
('martial-adept','Martial Adept','You learn two maneuvers from the Battle Master archetype and gain one superiority die (d6) to fuel them, regained on a short or long rest.','None'),
('medium-armor-master','Medium Armor Master','No disadvantage on Stealth while wearing medium armor, and max Dexterity bonus while wearing it becomes +3 instead of +2.','Proficiency with medium armor'),
('mobile','Mobile','Speed increases by 10 ft; when you use Dash, difficult terrain doesn''t cost extra movement; when you make a melee attack you don''t provoke opportunity attacks from that creature.','None'),
('moderately-armored','Moderately Armored','+1 Strength or Dexterity and proficiency with medium armor and shields.','Proficiency with light armor'),
('mounted-combatant','Mounted Combatant','Advantage on melee attacks against unmounted creatures smaller than your mount; can redirect attacks aimed at mount to yourself; mount doesn''t take damage on a successful Dex save (half on fail).','None'),
('observant','Observant','+1 Intelligence or Wisdom; can read lips; +5 bonus to passive Perception and passive Investigation.','None'),
('polearm-master','Polearm Master','When you attack with a glaive, halberd, pike, or quarterstaff, you can use a bonus action to attack with the butt end (1d4 bludgeoning). You also get an opportunity attack when a creature enters your reach.','None'),
('resilient','Resilient','Choose one ability score: +1 to that score and you gain proficiency in saving throws using it.','None'),
('ritual-caster','Ritual Caster','Choose a class: bard, cleric, druid, sorcerer, warlock, or wizard. You learn two 1st-level ritual spells from that class and can cast them as rituals; you can add more ritual spells found as scrolls or books.','Intelligence or Wisdom 13'),
('savage-attacker','Savage Attacker','Once per turn, when you roll weapon attack damage, you can reroll the damage dice and use either total.','None'),
('sentinel','Sentinel','When you hit a creature with an opportunity attack its speed drops to 0. Creatures within 5 ft provoke opportunity attacks even after Disengage. When a creature attacks someone other than you within 5 ft, you can make a reaction melee attack.','None'),
('sharpshooter','Sharpshooter','Ignore long-range penalty and three-quarters and half cover; optionally take -5 to hit for +10 damage on ranged attacks.','None'),
('shield-master','Shield Master','If you take the Attack action, add shield bash as a bonus action (1d4 + Str). Add shield''s AC bonus to Dex saves against spells that target only you. Use reaction to take no damage on a successful Dex save instead of half.','None'),
('skilled','Skilled','Gain proficiency in any combination of three skills or tools of your choice.','None'),
('skulker','Skulker','Can try to hide when lightly obscured; missing an attack while hiding doesn''t reveal you; dim light doesn''t impose disadvantage on Perception checks.','Dexterity 13'),
('spell-sniper','Spell Sniper','Choose a spellcasting class. Learn a cantrip from it that requires an attack roll. Double the range of ranged spell attacks; ranged spell attacks ignore half and three-quarters cover.','Spellcasting ability'),
('tavern-brawler','Tavern Brawler','+1 Strength or Constitution; proficient with improvised weapons; unarmed strikes deal 1d4 bludgeoning; can attempt to grapple as a bonus action after hitting with an unarmed strike or improvised weapon.','None'),
('tough','Tough','HP maximum increases by 2 per level (including retroactively for levels already gained).','None'),
('war-caster','War Caster','Advantage on Concentration saves; can perform somatic components with weapons/shield in hand; when a creature provokes an opportunity attack from you, you can cast a spell targeting it instead.','Spellcasting ability'),
('weapon-master','Weapon Master','+1 Strength or Dexterity and proficiency with four weapons of your choice.','None');
